gui: make 'flush_state' parameters explicit
Clang on macOS now complains about this:

  gui/osascript.c:335:17: error: a function declaration without a
    prototype is deprecated in all versions of C
    [-Werror,-Wstrict-prototypes]
    335 | void flush_state() { /* no-op for osascript */ }
        |                 ^
        |                  void