swap 'sprintf' for 'snprintf'
Clang on macOS complains about this:

  src/export.c:99:3: error: 'sprintf' is deprecated: This function is
    provided for compatibility reasons only.  Due to security concerns
    inherent in the design of sprintf(3), it is highly recommended that
    you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
     99 |   sprintf(tmp, "%s~", path);
        |   ^